name: PAIiM-Lab5

services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: paiim_db_5
    ports:
      - 1433:${DATABASE_PORT}
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DATABASE_PASSWORD}
      - MSSQL_PID=Developer
